# See application.yml for configuration
spring.datasource.url=jdbc:postgresql://dpg-d6ohd8ur433s73d1u9qg-a.oregon-postgres.render.com:5432/postgres_clzm
spring.datasource.username=postgres_clzm_user
spring.datasource.password=y87ejRIotTQnc9vWkyIsLtyEP2dvDLyD

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}