server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/local_services
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

app:
  upload:
    dir: uploads
